name: pages
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'docs/**'
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-20.04

    steps:
    - name: Clone cachepot repo
      uses: actions/checkout@v2

    - name: Use Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Setup mdbook-linkcheck
      run: |
        cargo install mdbook-linkcheck

    - name: Setup mdbook-graphviz
      run: |
        sudo apt install -y graphviz
        # FIXME: Don't specify git/rev once v0.1.4 is released to crates.io
        cargo install mdbook-graphviz --git https://github.com/dylanowen/mdbook-graphviz --rev 8e7f9d75823e5e64e3204e70a8d15e223e32fca9

    - name: Setup mdbook-mermaid
      run: |
        cargo install mdbook-mermaid

    - name: Build book.
      run: |
        mdbook build docs/book

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/book/book/html/
        cname: cachepot.cc
